name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      mysql:
        image: mariadb:10.6.17
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 10
    
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v2
      
    - name: Ruby のセットアップ
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'
        
    - name: 依存関係のインストール
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        
    - name: データベースの準備
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
      run: |
        export RAILS_ENV=production
        export DATABASE_URL=mysql2://$DB_USERNAME:$DB_PASSWORD@$DB_HOST/$DB_USERNAME
        sudo service mysql start
        sudo mysql --protocol=tcp -u mwzdqwaa_mfiles_db -pryota4729 -h 127.0.0.1
        bundle exec rake db:schema:load

    - name: アセットのビルド
      run: |
        export RAILS_ENV=production
        bundle exec rake assets:precompile
      
    - name: FTPS を使用してデプロイ
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: public/assets
        server-dir: ${{ secrets.FTP_REMOTE_DIR }}
        args: --delete


    - name: クリーンアップ
      run: |
        sudo service mysql stop  # MySQL サービスの停止