name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v2
      
    - name: Ruby のセットアップ
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'
        
    - name: 依存関係のインストール
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        
    - name: データベースの準備
      env:
        DB_USERNAME: root
        DB_PASSWORD: ""
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
      run: |
        export RAILS_ENV=production
        export DATABASE_URL=mysql2://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:$DB_PORT/githubactions_rails_production
        mysql -u $DB_USERNAME -p$DB_PASSWORD -h $DB_HOST -P $DB_PORT -e 'CREATE DATABASE IF NOT EXISTS githubactions_rails_production;'
        bundle exec rake db:schema:load

    - name: アセットのビルド
      run: |
        export RAILS_ENV=production
        bundle exec rake assets:precompile
      
    - name: FTPS を使用してデプロイ
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: public/assets
        server-dir: ${{ secrets.FTP_REMOTE_DIR }}
        args: --delete


    - name: クリーンアップ
      run: |
        sudo service mysql stop  # MySQL サービスの停止