name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      mysql:
        image: mariadb:10.6.17
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          # MYSQL_ALLOW_EMPTY_PASSWORD: yes
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 10
    
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v2
      
    - name: Ruby のセットアップ
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'
        
    - name: 依存関係のインストール
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    # - name: テスト用データベースの準備
    #   run: |
    #       cp config/database.ci.yml config/database.yml
    #       bundle exec rails db:create RAILS_ENV=test
    #       bundle exec rails db:migrate RAILS_ENV=test
  
    # - name: RSpecテスト
    #   run: bundle exec rspec spec/models spec/requests  spec/system 

    # - name: RuboCopテスト
    #   run: bundle exec rubocop

    - name: 環境変数の設定
      run: |
        export RAILS_ENV=production
        export DATABASE_URL=${{ secrets.DATABASE_URL }}
        export SECRET_KEY_BASE=${{ secrets.RAILS_SECRET_KEY_BASE }}

    - name: アセットのビルド
      run: |
        bundle exec rake assets:precompile
      
    - name: FTPS を使用してデプロイ
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: public/assets
        server-dir: ${{ secrets.FTP_REMOTE_DIR }}
        args: --delete